name: Testes Python de Temperatura

on:
  push:
    branches:
      - main 

jobs:
  build-and-test:
    name: Build e Testes em Python
    runs-on: ${{ matrix.os }} 

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.10', '3.12'] 

    steps:
    - name: Checkout do Código 
      uses: actions/checkout@v4

    - name: Configurar Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Executar Testes de Unidade 
      run: |
        python -m unittest test_conversor.py